/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        tertiary: "#a43a3a",
        "outline-variant": "#bbcabf",
        "surface-container": "#e7eefe",
        "on-secondary-fixed": "#002113",
        "on-primary-fixed-variant": "#005236",
        "primary-fixed": "#6ffbbe",
        "surface-container-high": "#e2e8f8",
        "on-surface": "#151c27",
        "surface-container-highest": "#dce2f3",
        "on-tertiary-fixed-variant": "#842225",
        "tertiary-fixed": "#ffdad7",
        "tertiary-fixed-dim": "#ffb3af",
        "on-primary-fixed": "#002113",
        "inverse-on-surface": "#ebf1ff",
        "on-secondary-fixed-variant": "#1e4f3a",
        "inverse-primary": "#4edea3",
        "on-tertiary-container": "#711419",
        "on-surface-variant": "#3c4a42",
        "on-background": "#151c27",
        error: "#ba1a1a",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#2a313d",
        surface: "#f9f9ff",
        background: "#f9f9ff",
        outline: "#6c7a71",
        "secondary-fixed": "#baeed1",
        "on-secondary-container": "#3c6c54",
        "on-error": "#ffffff",
        "primary-container": "#10b981",
        "surface-dim": "#d3daea",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#4edea3",
        primary: "#006c49",
        secondary: "#376850",
        "secondary-fixed-dim": "#9ed2b5",
        "on-primary-container": "#00422b",
        "on-primary": "#ffffff",
        "secondary-container": "#b7ebce",
        "surface-container-low": "#f0f3ff",
        "surface-tint": "#006c49",
        "on-tertiary-fixed": "#410005",
        "tertiary-container": "#fc7c78",
        "on-secondary": "#ffffff",
        "surface-variant": "#dce2f3",
        "surface-bright": "#f9f9ff",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        xl: "24px",
      },
    },
  },
};
